export const runtime = "nodejs";

export async function POST(req: Request) {
  try {
    const { to, subject, body, documentText, type } = await req.json();
    if (!to || !subject || !documentText) {
      return Response.json({ error: "Missing required fields" }, { status: 400 });
    }

    const resendKey = (process.env.RESEND_API_KEY ?? "").trim();
    if (!resendKey) {
      return Response.json({ error: "Email not configured" }, { status: 500 });
    }

    const typeLabel = type === "draft" ? "Document" : "Document Review";

    const html = `
      <div style="font-family:Georgia,serif;max-width:640px;margin:0 auto;padding:40px 24px;background:#f5f5f0;">
        <div style="background:#08111f;padding:28px 24px;text-align:center;border-radius:10px 10px 0 0;">
          <h1 style="color:#C9A84C;margin:0;font-size:22px;letter-spacing:2px;">LEX</h1>
          <p style="color:#8fa3c0;margin:6px 0 0;font-size:12px;letter-spacing:1px;">Legal Intelligence</p>
        </div>
        <div style="background:white;padding:36px 28px;border-radius:0 0 10px 10px;">
          ${body ? `<p style="color:#1a1a2e;font-size:14px;line-height:1.7;margin:0 0 28px;font-family:Georgia,serif;">${body.replace(/\n/g, '<br>')}</p>` : ''}
          <div style="background:#f8f9fa;padding:24px 20px;border-radius:8px;border-left:3px solid #C9A84C;">
            <p style="color:#1a1a2e;font-size:13px;line-height:1.8;margin:0;white-space:pre-wrap;font-family:Georgia,serif;">${documentText.replace(/\n/g, '<br>').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p>
          </div>
          <div style="margin-top:28px;padding-top:20px;border-top:1px solid #e5e7eb;text-align:center;">
            <p style="color:#8fa3c0;font-size:11px;margin:0;">${typeLabel} generated by Lex AI</p>
            <p style="color:#8fa3c0;font-size:10px;margin:4px 0 0;">This document was created by artificial intelligence. Please review with your legal practitioner.</p>
          </div>
        </div>
      </div>
    `;

    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${resendKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: "Lex AI <hello@saabai.ai>",
        to: [to],
        subject,
        html,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      return Response.json({ error: "Email failed", details: err }, { status: 500 });
    }

    return Response.json({ ok: true });
  } catch (err) {
    return Response.json({ error: String(err) }, { status: 500 });
  }
}
