/**
 * Rex Pay Redirect
 *
 * Called when a customer clicks "Lock it in →" in the Rex chat widget.
 * Creates a WooCommerce pending order via rex-checkout and redirects straight
 * to the WooCommerce order-pay page — no product page, no cart browsing needed.
 *
 * For multi-item orders the customer says "yes" in chat, which triggers
 * createCheckout directly. This endpoint handles single-item click-through.
 *
 * Security note: priceExGst is passed via URL and trusted as-is. WooCommerce
 * creates a pending order at that price and Stripe charges that amount.
 * The URL is generated by Rex from a live getPrice result so manipulation
 * risk is low in practice. Sign the params if tighter security is needed.
 */

export const runtime = "nodejs";

const FALLBACK = "https://www.plasticonline.com.au/shop/";

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);

  const material    =                    searchParams.get("material")    ?? "";
  const colour      =                    searchParams.get("colour")      ?? "";
  const thicknessMm = parseFloat(       searchParams.get("thicknessMm") ?? "0");
  const widthMm     = parseFloat(       searchParams.get("widthMm")     ?? "0");
  const heightMm    = parseFloat(       searchParams.get("heightMm")    ?? "0");
  const qty         = Math.max(1, parseInt(searchParams.get("qty")      ?? "1"));
  const priceExGst  = parseFloat(       searchParams.get("priceExGst")  ?? "0");

  if (!material || !thicknessMm || !widthMm || !heightMm || !priceExGst) {
    return Response.redirect(FALLBACK, 302);
  }

  try {
    const base = process.env.NEXT_PUBLIC_BASE_URL ?? "https://saabai-site.vercel.app";

    const res = await fetch(`${base}/api/rex-checkout`, {
      method:  "POST",
      headers: { "Content-Type": "application/json" },
      body:    JSON.stringify({
        items: [{ material, colour, thicknessMm, widthMm, heightMm, qty, priceExGst }],
      }),
    });

    if (!res.ok) throw new Error(`rex-checkout returned ${res.status}`);

    const data = await res.json();

    if (data.checkoutUrl) {
      return Response.redirect(data.checkoutUrl, 302);
    }

    throw new Error(data.error ?? "No checkoutUrl returned");

  } catch (err) {
    console.error("[rex-pay]", err);
    return Response.redirect(FALLBACK, 302);
  }
}
